version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  sushant-api:
    container_name: sushant-api
    image: sushant5x/fullstack-app-backend:latest
#    env_file:
#      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  sushant-react:
    container_name: sushant-react
    image: sushant5x/fullstack-app-frontend:latest
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - sushant-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: