networks:
  mynetwork:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d customer" ]
      interval: 10s
      retries: 5
      start_period: 10s

  sushant-api:
    container_name: sushant-api
    image: sushant5x/fullstack-app-backend:latest
#    env_file:
#      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/customer
    ports:
      - "8088:8080"
    networks:
      - mynetwork
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  sushant-react:
    container_name: sushant-react
    image: sushant5x/fullstack-app-frontend:latest
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:3000"
    depends_on:
      - sushant-api
    networks:
      - mynetwork
    restart: unless-stopped



volumes:
  postgres: