services:
#  db:
#    container_name: postgres
#    image: postgres:14.1
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root123
#      PGDATA: /data/postgres
#    volumes:
#      - db:/data/postgres
#    ports:
#      - "5332:5432"
#    networks:
#      - db
#    restart: unless-stopped

  sushant-api:
    container_name: sushant-api
    image: sushant/sushant-api
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${RDS_HOST}:5432/${RDS_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
    ports:
      - "8088:8080"
    networks:
      - db
#    depends_on:
#      - db
    restart: unless-stopped

  sushant-react:
    container_name: sushant-react
    image: sushant/sushant-react
    build:
      context: frontend/react
      args:
        api_base_url: http://fullstack-db-env.eba-y3epwet3.ap-south-1.elasticbeanstalk.com
    ports:
      - "3000:5173"
    depends_on:
      - sushant-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
