aws:
  s3:
    mock: false

spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOST}:5432/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver
